AWSTemplateFormatVersion: "2010-09-09"
Description: "Server Infrastructure with Launch Template, Auto Scaling Group, and Application Load Balancer"

Parameters:
  VpcId:
    Description: VPC ID for the ALB and servers
    Type: AWS::EC2::VPC::Id

  PublicSubnets:
    Description: Comma-separated list of public subnet IDs for the ALB
    Type: List<AWS::EC2::Subnet::Id>

  PrivateSubnets:
    Description: Comma-separated list of private subnet IDs for the servers
    Type: List<AWS::EC2::Subnet::Id>

  KeyName:
    Description: Key pair name for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  SshCidrIp:
    Type: String
    Default: 0.0.0.0/0
    Description: IP range for SSH access

Resources:
  # IAM Role for EC2 Instances
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

  # IAM Instance Profile
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole
  # Launch Template for EC2 Instances
  TwitterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: TwitterServiceTemplate
      LaunchTemplateData:
        InstanceType: t2.micro
        KeyName: !Ref KeyName
        ImageId: !Sub "resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 8
              VolumeType: gp2
              DeleteOnTermination: true
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        UserData: 
          Fn::Base64: !Sub |
            #!/bin/bash
            # Update the system
            yum update -y

            # Install Apache web server
            yum install -y httpd

            # Start and enable Apache
            systemctl start httpd
            systemctl enable httpd

            # Create a simple index.html
            echo "<html>
            <head>
              <title>Twitter Service</title>
            </head>
            <body>
              <h1>Welcome to the Twitter Service</h1>
              <p>This is a placeholder page for the Twitter application.</p>
            </body>
            </html>" > /var/www/html/index.html

            # Ensure proper permissions
            chmod 644 /var/www/html/index.html

        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: TwitterServiceInstance

  # Auto Scaling Group
  TwitterAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: TwitterServiceASG
      LaunchTemplate:
        LaunchTemplateId: !Ref TwitterLaunchTemplate
        Version: !GetAtt TwitterLaunchTemplate.LatestVersionNumber
      MinSize: 2
      MaxSize: 2
      DesiredCapacity: 2
      VPCZoneIdentifier: 
        Fn::Split:
            - ","
            - !ImportValue "PrivateSubnets"
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      Tags:
        - Key: Name
          Value: TwitterServiceInstance
          PropagateAtLaunch: true
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300

# Security Group for Load Balancer
  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic to the Load Balancer
      VpcId:  
        Fn::ImportValue: "VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref SshCidrIp
      Tags:
        - Key: Name
          Value: LBSecurityGroup

  # Security Group for Web Servers
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic from Load Balancer to Web Servers
      VpcId: 
        Fn::ImportValue: "VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref LBSecurityGroup
      Tags:
        - Key: Name
          Value: WebServerSecurityGroup


  # ALB Resource
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyApplicationALB
      Scheme: internet-facing
      Subnets: 
        Fn::Split:
          - ","
          - !ImportValue "PublicSubnets"
      SecurityGroups: 
        - !Ref LBSecurityGroup
      Tags:
        - Key: Name
          Value: Application-ALB

  # Target Group for ALB
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      VpcId: !ImportValue  "VpcId"
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: Application-TargetGroup

  # Listener for ALB
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
# ALB Listener Rule
  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        ListenerArn: !Ref ALBListener
        Conditions:
          - Field: path-pattern
            Values:
              - /twitter
        Actions:
          - Type: forward
            TargetGroupArn: !Ref ALBTargetGroup
        Priority: 1

Outputs:
  ALBDNSName:
    Description: DNS Name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  TwitterServiceASGName:
    Description: Name of the Auto Scaling Group
    Value: !Ref TwitterAutoScalingGroup
